import Head from "next/head";
import { useState } from "react";
import { Navbar } from "./components/Navbar";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>ILOS 💜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen dark:bg-gray-900 transition-colors">
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
        <main>
          <p className="text-xl">Hello World</p>
        </main>
      </div>
    </div>
  );
}
